### ISSUE TITLE
Crash On Latest version of Clubhouse 

### ISSUE THREAD

**Issue by AAA-10** [eclair4151/SearchForClubhouse#1]
When I search the app close, can you fix it 
Latest Version number: 0.1.33
———————————
IOS: 14.3
Iphone XS
Unc0ver: 6.1.2

Thanks

**Comment by AAA-10** [comment]
IOS: 14.3
Iphone XS

**Comment by eclair4151** [comment]
This has already been fixed. You can download version 0.0.3 from the packages folder or wait for the bigboss repo to update in the next few days.

**Comment by eclair4151** [comment]
Thanks for the sponsor ❤️
